## Pipeline Script 


Inputs: Group CEST and nmap data output from pyGluCEST as well as demographic data from _________. 
Outputs: Compiled dataframes with GluCEST and nmap data. Trimmed based on number of people with sufficient data.

    Trimmed subject-wise dfs: e.g., cestmat (outpath + 'trimmed_cestmat' + dataset + atlas + '.csv')
    Long form dfs: e.g., long_df (outpath + 'longform_grpdf' + dataset + '_' + atlas + '.csv')
         Also have version with standard nmap values
    Mean dfs: e.g., grouped_df (outpath + 'means_' + dataset + '_' + atlas + '.csv')

### Import Packages

In [1]:
import os
import glob
import numpy as np
import pandas as pd
#import network_fcon as fc
import scipy as sp
from scipy.stats import pearsonr
from scipy.stats import linregress
import seaborn as sns
import matplotlib.pyplot as plt
import re
from nilearn.datasets import fetch_atlas_schaefer_2018
from netneurotools.datasets import fetch_cammoun2012

In [2]:
lobe_dict = {
    "caudalanteriorcingulate":"frontal",
    "cuneus":"occipital",
    "frontalpole":"frontal",
    "isthmuscingulate":"parietal",
    "lingual":"occipital",
    "paracentral":"frontal",
    "posteriorcingulate":"parietal",
    "precuneus":"parietal",
    "rostralanteriorcingulate":"frontal",
    "superiorfrontal":"frontal"
}
    
def add_lobe(df):
    if "lobe" in df.columns:
        return df
    else:
        parcel_part = df['Parcel'].str.extract(r'(.*?)_')
        df["Lobe"] = [lobe_dict[key] for key in parcel_part[0] if key in lobe_dict]
        return df

### Define paths and variables

In [2]:
# Set variables
dataset = 'longglucest_outputmeasures2'
atlas = 'atl-Cammoun2012_res-500'
nmaps = ["NMDA", "mGluR5", "GABA"]
maps = ["cest", "NMDA", "mGluR5", "GABA"]
normalize_cest = True

# Set paths
inpath = "/Users/pecsok/Desktop/ImageData/PMACS_remote/data/nmaps/" + dataset
outpath = "/Users/pecsok/Desktop/ImageData/PMACS_remote/data/nmaps/analyses/" + atlas
os.makedirs(os.path.join(outpath), exist_ok=True)

# Read in data
cestmat = pd.read_csv(inpath + "/all_subs_GluCEST_" + atlas + "_UNI.csv", sep=',')
NMDAmat = pd.read_csv(inpath + "/all_subs_NMDA_normalized_" + atlas + "_UNI.csv", sep=',')
mGluR5mat = pd.read_csv(inpath + "/all_subs_mGluR5_normalized_" + atlas + "_UNI.csv", sep=',')
GABAmat = pd.read_csv(inpath + "/all_subs_GABA_normalized_" + atlas + "_UNI.csv", sep=',')

# Set indices and correct column names
cestmat.set_index('Subject', inplace = True)
NMDAmat.set_index('Subject', inplace = True)
GABAmat.set_index('Subject', inplace = True)
mGluR5mat.set_index('Subject', inplace = True)
dfs = [cestmat, NMDAmat, mGluR5mat, GABAmat]

# Load in standardized nmap data for alternative approach.
receptor_df = pd.read_csv("/Users/pecsok/projects/Neuromaps/pecsok_pfns/neuromaps/results/receptor_data_scale1000_17.csv", sep=',')
receptor_df = pd.read_csv("/Users/pecsok/projects/Neuromaps/pecsok_pfns/neuromaps/results/receptor_data_cammoun2012_scale500.csv", sep=',')

In [3]:
# Remove Subcortical ROIs
cam = fetch_cammoun2012()
info = pd.read_csv(cam['info'], sep=',')
info = info[info['scale']== 'scale500']
#labels = info['label'][info['structure']=='cortex'].values
#labels = info['label'][info['structure']=='cortex'].values + hemisphere
hemisphere = info['hemisphere'][info['structure']=='subcortex'].values
subcortex = info['label'][info['structure']=='subcortex'].values + hemisphere
print(subcortex.shape)

(15,)

In [4]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
#print(cestmat)

## Trim Data

In [5]:
# ID parcels with < 20 voxels* 
for i, col in enumerate(cestmat.columns):
    if 'NZcount' in col:
        # Set mean col to nan
        mean_col = cestmat.columns[i - 1]
        sigma_col = cestmat.columns[i + 1]
        cestmat[mean_col] = np.where(cestmat[col] < 20, np.nan, cestmat[mean_col])
        cestmat[sigma_col] = np.where(cestmat[col] < 20, np.nan, cestmat[sigma_col])
        cestmat[col] = np.where(cestmat[col] < 20, np.nan, cestmat[col])       
columns = cestmat.columns[cestmat.notnull().sum() > len(cestmat)*.75]
print(cestmat.shape)

# Trim all dfs based on column filter
cestmat= cestmat[columns]
NMDAmat= NMDAmat[columns]
GABAmat= GABAmat[columns]
mGluR5mat= mGluR5mat[columns]
print(cestmat.shape)

# ID subjects missing >65% of remaining GluCEST parcels
sparse_subjs = cestmat[cestmat.isna().sum(axis=1) > cestmat.shape[1] * 0.65].index

# Trim all dfs based on row filter
cestmat = cestmat.drop(index=sparse_subjs)
NMDAmat = NMDAmat.drop(index=sparse_subjs)
GABAmat = GABAmat.drop(index=sparse_subjs)
mGluR5mat = mGluR5mat.drop(index=sparse_subjs)
print(cestmat.shape)

# Remove subcortical ROIs
if atlas == 'atl-Cammoun2012_res-500':
    cestmat = cestmat.loc[:, ~cestmat.columns.str.contains('|'.join(subcortex), na=False)]
    NMDAmat = NMDAmat.loc[:, ~NMDAmat.columns.str.contains('|'.join(subcortex), na=False)]
    GABAmat = GABAmat.loc[:, ~GABAmat.columns.str.contains('|'.join(subcortex), na=False)]
    mGluR5mat = mGluR5mat.loc[:, ~mGluR5mat.columns.str.contains('|'.join(subcortex), na=False)]
print(cestmat.shape)

# Temporary: Remove mysterious zeros in nmap dataframes
dfs = [NMDAmat, mGluR5mat, GABAmat]
for i in range(len(dfs)):
    df = dfs[i]
    df.replace(0, np.nan, inplace=True)

# Save trimmed dfs
cestmat.to_csv(outpath + '/trimmed_cestmat' + dataset + atlas + '.csv', index=True)
NMDAmat.to_csv(outpath + '/trimmed_NMDAmat' + dataset + atlas + '.csv', index=True)
GABAmat.to_csv(outpath + '/trimmed_GABAmat' + dataset + atlas + '.csv', index=True)
mGluR5mat.to_csv(outpath + '/trimmed_mGluR5mat' + dataset + atlas + '.csv', index=True)

(182, 725)
(182, 167)
(176, 167)
(176, 158)

## Add Cortical Lobe Labels

In [6]:
cestmat.head()

,Unnamed: 0,frontalpole_1R NZMean,frontalpole_1R NZcount,frontalpole_1R NZSigma,superiorfrontal_40R NZMean,superiorfrontal_40R NZcount,superiorfrontal_40R NZSigma,superiorfrontal_7R NZMean,superiorfrontal_7R NZcount,superiorfrontal_7R NZSigma,...,cuneus_3R NZMean,cuneus_3R NZcount,cuneus_3R NZSigma,cuneus_5R NZMean,cuneus_5R NZcount,cuneus_5R NZSigma,precuneus_15R NZMean,precuneus_15R NZcount,precuneus_15R NZSigma,group
Subject,,,,,,,,,,,,,,,,,,,,,
100522_12003,0,5.533474,32.0,2.188992,4.299698,49.0,2.442113,5.721321,45.0,2.229686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TD/NC
100522_12371,1,5.459877,28.0,2.447069,5.136139,39.0,2.566857,6.545109,48.0,2.199931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TD/NC
100522_12783,2,4.864008,31.0,1.728823,6.269497,51.0,2.130490,6.568427,62.0,1.743864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TD/NC
102041_12037,3,7.210485,69.0,2.443378,7.443285,66.0,1.365854,7.582340,60.0,1.850772,...,7.258384,41.0,2.249775,8.277832,30.0,1.703806,NaN,NaN,NaN,PRO/CHR
102041_12500,4,9.612453,71.0,2.522940,7.381907,63.0,1.860883,8.027369,56.0,1.492858,...,9.191903,42.0,1.569125,9.379838,34.0,1.157970,NaN,NaN,NaN,PRO/CHR

## Normalize GluCEST

In [7]:
# Step 1: Select columns that contain 'NZMean'
if normalize_cest:
    nzmean_columns = [col for col in cestmat.columns if 'NZMean' in col]
    
    # Step 2: Calculate mean and std deviation for each subject (row-wise) across selected columns
    cestmat['Subject_Avg_NZMean'] = cestmat[nzmean_columns].mean(axis=1)
    cestmat['Subject_Std_NZMean'] = cestmat[nzmean_columns].std(axis=1)
    
    # Step 3: Calculate z-scores for all selected columns at once and store them in a new dataframe
    zscore_df = (cestmat[nzmean_columns].sub(cestmat['Subject_Avg_NZMean'], axis=0)
                 .div(cestmat['Subject_Std_NZMean'], axis=0))

    # Step 4: Concatenate the z-scores dataframe to the original cestmat dataframe
    cestmat = pd.concat([cestmat['group'], zscore_df], axis=1)
    cestmat.to_csv(outpath + '/grp_df_means_std_normalized_' + dataset + '_' + atlas + '.csv', index=False)

/var/folders/kk/w6xmtt2d55xfbxvb6wcqhq580000gp/T/ipykernel_45761/2696464397.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cestmat['Subject_Avg_NZMean'] = cestmat[nzmean_columns].mean(axis=1)
/var/folders/kk/w6xmtt2d55xfbxvb6wcqhq580000gp/T/ipykernel_45761/2696464397.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cestmat['Subject_Std_NZMean'] = cestmat[nzmean_columns].std(axis=1)

In [8]:
cestmat.head()

,group,frontalpole_1R NZMean,superiorfrontal_40R NZMean,superiorfrontal_7R NZMean,superiorfrontal_23R NZMean,superiorfrontal_10R NZMean,superiorfrontal_39R NZMean,superiorfrontal_29R NZMean,superiorfrontal_1R NZMean,superiorfrontal_30R NZMean,...,paracentral_11R NZMean,precuneus_7R NZMean,precuneus_14R NZMean,precuneus_11R NZMean,precuneus_8R NZMean,precuneus_18R NZMean,precuneus_13R NZMean,cuneus_3R NZMean,cuneus_5R NZMean,precuneus_15R NZMean
Subject,,,,,,,,,,,,,,,,,,,,,
100522_12003,TD/NC,-1.573371,-2.511252,-1.430575,-0.694887,-1.330532,-1.444310,-0.465021,-1.045952,-0.017369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100522_12371,TD/NC,-2.009694,-2.268959,-1.140590,-0.077094,-1.079176,-1.159484,0.090207,-0.169905,0.008017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100522_12783,TD/NC,-2.328360,-1.216252,-0.979721,0.337610,-0.339099,-1.239030,-0.354976,0.366586,-0.664460,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102041_12037,PRO/CHR,-0.686951,-0.495555,-0.381232,-0.279610,-0.312438,-0.953016,-1.139706,-0.405014,-0.511538,...,0.784675,NaN,0.122211,0.234537,NaN,-0.786964,-0.379243,-0.647571,0.190564,NaN
102041_12500,PRO/CHR,2.060564,-0.101545,0.524113,0.030853,-0.082949,0.184125,-0.712321,0.192955,-0.690277,...,-0.960837,NaN,0.274427,-0.385214,-0.418084,0.905397,-0.489707,1.652917,1.835086,NaN

## Make classic grp_df

In [9]:
# First, add datatype to column names so can be distinguished later.
cestmat2=cestmat.copy()
NMDAmat2=NMDAmat.copy()
GABAmat2=GABAmat.copy()
mGluR5mat2=mGluR5mat.copy()
cestmat2.columns = [f"GluCEST_{col}" if "NZ" in col else col for col in cestmat2.columns]
NMDAmat2.columns = [f"NMDA_{col}" if "NZ" in col else col for col in NMDAmat2.columns]
GABAmat2.columns = [f"GABA_{col}" if "NZ" in col else col for col in GABAmat2.columns]
mGluR5mat2.columns = [f"mGluR5_{col}" if "NZ" in col else col for col in mGluR5mat2.columns]

# Align dataframes by "Subject" index and concatenate along columns
grp_df = cestmat2.join(NMDAmat2.filter(like='NZ'), how='left')
grp_df = grp_df.join(GABAmat2.filter(like='NZ'), how='left')
grp_df = grp_df.join(mGluR5mat2.filter(like='NZ'), how='left')

# Save grpd_df
grp_df.to_csv(outpath + '/grp_df_' + dataset + atlas + '.csv', index=True)
#print(cestmat)

In [10]:
#print(NMDAmat)

## Make longform group df

In [11]:
# Make longform group df
# Get list of parcel names
parcels = cestmat.filter(like="NZMean").columns.tolist()

# Melt cestmat to get Glu data in long format
cestlong = cestmat.reset_index().melt(id_vars='Subject', value_vars=parcels, 
                                      var_name='Parcel', value_name='GluCEST')

# Melt nmap data. Fix!! turn into loop later.
NMDAlong = NMDAmat.reset_index().melt(id_vars='Subject', value_vars=parcels, 
                                       var_name='Parcel', value_name='NMDA')
GABAlong = GABAmat.reset_index().melt(id_vars='Subject', value_vars=parcels, 
                                       var_name='Parcel', value_name='GABA')
mGluR5long = mGluR5mat.reset_index().melt(id_vars='Subject', value_vars=parcels, 
                                       var_name='Parcel', value_name='mGluR5')

# Merge the long-form dataframes based on Subject and Parcel
long_df = pd.merge(cestlong, NMDAlong,  on=['Subject', 'Parcel'])
long_df = pd.merge(long_df, GABAlong,  on=['Subject', 'Parcel'])
long_df = pd.merge(long_df, mGluR5long,  on=['Subject', 'Parcel'])

# Add diagnostic group
diag_df = cestmat['group']
long_df = pd.merge(long_df, diag_df, on='Subject')
long_df['hstatus'] = np.where(long_df['group'].isin(['TD/NC']), 'HC', 'PSY')
#print(long_df)

# Save longformdf
long_df.to_csv(outpath + '/longform_grpdf_' + dataset + atlas + '.csv', index=True)

### Make mean group dfs by diagnosis

In [12]:
# Make mean group dfs by diagnosis
grouped_subj = long_df.groupby(['Parcel', 'hstatus']).agg(
    CEST_avg=('GluCEST', 'mean'),
    NMDA=('NMDA', 'mean'),
    mGluR5=('mGluR5', 'mean'),
    GABA=('GABA', 'mean')
).reset_index()
print(grouped_subj)
# Save
grouped_subj.to_csv(outpath + '/means_subjectnmaps_' + dataset + '_' + atlas + '.csv', index=False)

                                Parcel hstatus  CEST_avg      NMDA    mGluR5  \
0    caudalanteriorcingulate_5R NZMean      HC  0.140048 -1.047351  0.278927
1    caudalanteriorcingulate_5R NZMean     PSY -0.011085 -1.210817  0.019354
2                     cuneus_3R NZMean      HC  0.884299  0.750100  1.195524
3                     cuneus_3R NZMean     PSY  0.305783  0.808305  1.227833
4                     cuneus_5R NZMean      HC  1.411665  0.029143  0.314619
..                                 ...     ...       ...       ...       ...
99           superiorfrontal_7R NZMean     PSY -0.455633  0.716904  1.076864
100          superiorfrontal_8R NZMean      HC -0.857712  0.380748  0.482610
101          superiorfrontal_8R NZMean     PSY -0.800876  0.242487  0.391164
102          superiorfrontal_9R NZMean      HC -0.154002 -0.110998  0.021254
103          superiorfrontal_9R NZMean     PSY -0.372532 -0.306964 -0.112934

         GABA
0   -0.089857
1   -0.331406
2    1.543468
3    1.582484
4    1.130346
..        ...
99   0.973271
100  0.509534
101  0.428549
102 -0.067384
103 -0.190129

[104 rows x 6 columns]

# REPEAT USING STANDARD NMAPS

In [13]:
"""
from netneurotools.datasets import fetch_cammoun2012

# Import and add parcel labels to standard receptor_df
if atlas == 'schaefer':
    schaefer = fetch_atlas_schaefer_2018(n_rois=1000, yeo_networks=17)
    labels = schaefer.labels
    labels = [label.decode('utf-8') for label in labels]
    receptor_df.index = labels
    receptor_df.index.name = 'Parcel'

if atlas == 'cammoun2012':
"""

receptor_df.rename(columns={'GABAa': 'GABA'}, inplace=True)
print(receptor_df)   

# Chop up receptor_df by map
NMDAmat = receptor_df[["Parcel","NMDA"]]
GABAmat = receptor_df[["Parcel","GABA"]]
mGluR5mat = receptor_df[["Parcel","mGluR5"]]

#print(NMDAmat)

                        Parcel      NMDA    mGluR5      GABA
0      lateralorbitofrontal_9R -0.020868  0.164621 -0.150228
1     lateralorbitofrontal_11R  0.366013 -0.085390  0.170483
2      lateralorbitofrontal_5R  1.171849  1.015446  1.317157
3      lateralorbitofrontal_6R  0.715088 -0.055909 -0.026400
4      lateralorbitofrontal_7R -0.125005  0.105069  0.344259
...                        ...       ...       ...       ...
1010                 pallidumL  1.184228 -2.200435 -3.248923
1011            accumbensareaL  0.632115  0.061453 -0.237722
1012              hippocampusL  0.855395 -1.009223 -1.039651
1013                 amygdalaL  0.109529 -0.782412 -0.971487
1014                brainstemL -0.798938 -4.706040 -5.108990

[1015 rows x 4 columns]

### Make classic grp_df

In [14]:
# Transpose receptor maps.
nmda = NMDAmat.T
gaba = GABAmat.T
mglur5 = mGluR5mat.T

print(nmda)
# Keep only parcels contained in cestmat
cestmat_regions = [col.replace(' NZMean', '') for col in cestmat.columns if ' NZMean' in col]
nmda_filtered = nmda[[col for col in nmda.columns if col in cestmat_regions]]
gaba_filtered = gaba[[col for col in gaba.columns if col in cestmat_regions]]
mglur5_filtered = mglur5[[col for col in mglur5.columns if col in cestmat_regions]]

# Filtered columns
nmda_filtered.columns = [f"NMDA_{col}" for col in nmda_filtered.columns]
gaba_filtered.columns = [f"GABA_{col}" for col in gaba_filtered.columns]
mglur5_filtered.columns = [f"mGluR5_{col}" for col in mglur5_filtered.columns]

# Repeat values for length of cestmat
nmda_repeated = pd.concat([nmda_filtered] * len(cestmat), ignore_index=True)
gaba_repeated = pd.concat([gaba_filtered] * len(cestmat), ignore_index=True)
mglur5_repeated = pd.concat([mglur5_filtered] * len(cestmat), ignore_index=True)

print(nmda_repeated)
# Concatenate
grp_df_std = pd.concat([cestmat2, nmda_repeated, gaba_repeated, mglur5_repeated], axis=1)

# Save grp_df_std
grp_df_std.to_csv(outpath + '/grp_df_std' + dataset + atlas + '.csv', index=True)
print(grp_df_std.head())

                           0                         1     \
Parcel  lateralorbitofrontal_9R  lateralorbitofrontal_11R
NMDA                  -0.020868                  0.366013

                           2                        3     \
Parcel  lateralorbitofrontal_5R  lateralorbitofrontal_6R
NMDA                   1.171849                 0.715088

                           4                         5     \
Parcel  lateralorbitofrontal_7R  lateralorbitofrontal_10R
NMDA                  -0.125005                  0.039044

                           6                         7     \
Parcel  lateralorbitofrontal_4R  lateralorbitofrontal_17R
NMDA                   1.248462                   0.37993

                           8                         9     ...       1005  \
Parcel  lateralorbitofrontal_8R  lateralorbitofrontal_15R  ...  insula_3L
NMDA                  -0.529395                  0.130049  ...  -0.166495

              1006             1007      1008      1009       1010  \
Parcel  insula_17L  thalamusproperL  caudateL  putamenL  pallidumL
NMDA      0.578973         1.630587  0.746623  1.444847   1.184228

                  1011          1012       1013        1014
Parcel  accumbensareaL  hippocampusL  amygdalaL  brainstemL
NMDA          0.632115      0.855395   0.109529   -0.798938

[2 rows x 1015 columns]
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[352 rows x 0 columns]
                group  GluCEST_frontalpole_1R NZMean  \
100522_12003    TD/NC                      -1.573371
100522_12371    TD/NC                      -2.009694
100522_12783    TD/NC                      -2.328360
102041_12037  PRO/CHR                      -0.686951
102041_12500  PRO/CHR                       2.060564

              GluCEST_superiorfrontal_40R NZMean  \
100522_12003                           -2.511252
100522_12371                           -2.268959
100522_12783                           -1.216252
102041_12037                           -0.495555
102041_12500                           -0.101545

              GluCEST_superiorfrontal_7R NZMean  \
100522_12003                          -1.430575
100522_12371                          -1.140590
100522_12783                          -0.979721
102041_12037                          -0.381232
102041_12500                           0.524113

              GluCEST_superiorfrontal_23R NZMean  \
100522_12003                           -0.694887
100522_12371                           -0.077094
100522_12783                            0.337610
102041_12037                           -0.279610
102041_12500                            0.030853

              GluCEST_superiorfrontal_10R NZMean  \
100522_12003                           -1.330532
100522_12371                           -1.079176
100522_12783                           -0.339099
102041_12037                           -0.312438
102041_12500                           -0.082949

              GluCEST_superiorfrontal_39R NZMean  \
100522_12003                           -1.444310
100522_12371                           -1.159484
100522_12783                           -1.239030
102041_12037                           -0.953016
102041_12500                            0.184125

              GluCEST_superiorfrontal_29R NZMean  \
100522_12003                           -0.465021
100522_12371                            0.090207
100522_12783                           -0.354976
102041_12037                           -1.139706
102041_12500                           -0.712321

              GluCEST_superiorfrontal_1R NZMean  \
100522_12003                          -1.045952
100522_12371                          -0.169905
100522_12783                           0.366586
102041_12037                          -0.405014
102041_12500                           0.192955

              GluCEST_superiorfrontal_30R NZMean  ...  \
100522_12003                           -0.017369  ...
100522_12371                            0.008017  ...
100522_12783                           -0.664460  ...
102041_12037                           -0.511538  ...
102041_12500                           -0.690277  ...

              GluCEST_paracentral_11R NZMean  GluCEST_precuneus_7R NZMean  \
100522_12003                             NaN                          NaN
100522_12371                             NaN                          NaN
100522_12783                             NaN                          NaN
102041_12037                        0.784675                          NaN
102041_12500                       -0.960837                          NaN

              GluCEST_precuneus_14R NZMean  GluCEST_precuneus_11R NZMean  \
100522_12003                           NaN                           NaN
100522_12371                           NaN                           NaN
100522_12783                           NaN                           NaN
102041_12037                      0.122211                      0.234537
102041_12500                      0.274427                     -0.385214

              GluCEST_precuneus_8R NZMean  GluCEST_precuneus_18R NZMean  \
100522_12003                          NaN                           NaN
100522_12371                          NaN                           NaN
100522_12783                          NaN                           NaN
102041_12037                          NaN                     -0.786964
102041_12500                    -0.418084                      0.905397

              GluCEST_precuneus_13R NZMean  GluCEST_cuneus_3R NZMean  \
100522_12003                           NaN                       NaN
100522_12371                           NaN                       NaN
100522_12783                           NaN                       NaN
102041_12037                     -0.379243                 -0.647571
102041_12500                     -0.489707                  1.652917

              GluCEST_cuneus_5R NZMean  GluCEST_precuneus_15R NZMean
100522_12003                       NaN                           NaN
100522_12371                       NaN                           NaN
100522_12783                       NaN                           NaN
102041_12037                  0.190564                           NaN
102041_12500                  1.835086                           NaN

[5 rows x 53 columns]

### Make Longform df

In [15]:
# Make longform df using standardized nmaps values

# Get list of parcel names
parcels = cestmat.filter(like="NZMean").columns.tolist()

# Keep relevant columns from long_df and rename parcels
longdf_cest = long_df[["Subject","Parcel","GluCEST","group","hstatus"]]
longdf_cest = longdf_cest.replace(' NZMean', '', regex=True)

#longdf_cest["Parcel"] = longdf_cest["Parcel"].str.replace(' NZMean', '', regex=False)

# Convert receptor_df from wide to long format for merging
nmda_long = NMDAmat.reset_index().melt(id_vars='Parcel', var_name='Receptor1', value_name='NMDA_standard')
gaba_long = GABAmat.reset_index().melt(id_vars='Parcel', var_name='Receptor2', value_name='GABA_standard')
mglur5_long = mGluR5mat.reset_index().melt(id_vars='Parcel', var_name='Receptor3', value_name='mGluR5_standard')

long_df_std = pd.merge(longdf_cest, NMDAmat, on=["Parcel"])
long_df_std = pd.merge(long_df_std, GABAmat, on = ["Parcel"])
long_df_std = pd.merge(long_df_std, mGluR5mat, on = ["Parcel"])

# Save the longform dataframe to a CSV
long_df_std.to_csv(outpath + '/longform_grpdf_std_' + dataset + '_' + atlas + '.csv', index=False)

### Make mean df by diagnosis

In [37]:
# Make mean group dfs by diagnosis
# Standard nmap data
grouped_std = long_df_std.groupby(['Parcel', 'hstatus']).agg(
    CEST_avg=('GluCEST', 'mean'),
    NMDA=('NMDA', 'mean'),
    mGluR5=('mGluR5', 'mean'),
    GABA=('GABA', 'mean')
).reset_index()
grouped_std = add_lobe(grouped_std)
print(grouped_std)
grouped_std.to_csv(outpath + '/means_std_' + dataset + '_' + atlas + '.csv', index=False)

                          Parcel hstatus  CEST_avg      NMDA    mGluR5  \
0     caudalanteriorcingulate_5R      HC  0.140048 -0.026330  1.229935
1     caudalanteriorcingulate_5R     PSY -0.011085 -0.026330  1.229935
2                      cuneus_3R      HC  0.884299 -0.522157  0.053661
3                      cuneus_3R     PSY  0.305783 -0.522157  0.053661
4                      cuneus_5R      HC  1.411665  0.046650  0.220775
5                      cuneus_5R     PSY  0.963478  0.046650  0.220775
6                 frontalpole_1R      HC -0.475798 -2.137305 -0.306475
7                 frontalpole_1R     PSY  0.129303 -2.137305 -0.306475
8            isthmuscingulate_1R      HC  0.265007  0.862035  0.410423
9            isthmuscingulate_1R     PSY  0.302260  0.862035  0.410423
10           isthmuscingulate_2R      HC  0.592127  1.319292  1.994640
11           isthmuscingulate_2R     PSY  0.723430  1.319292  1.994640
12           isthmuscingulate_3R      HC  0.098472  0.358761 -0.140923
13           isthmuscingulate_3R     PSY  0.257665  0.358761 -0.140923
14           isthmuscingulate_4R      HC  0.246605  0.665040 -0.384585
15           isthmuscingulate_4R     PSY  0.520684  0.665040 -0.384585
16                   lingual_11R      HC  1.179280  0.894964 -0.389795
17                   lingual_11R     PSY  0.804932  0.894964 -0.389795
18                   lingual_13R      HC  1.987714  0.758787 -0.223504
19                   lingual_13R     PSY  1.432024  0.758787 -0.223504
20               paracentral_11R      HC -0.106498  0.711784  1.030253
21               paracentral_11R     PSY -0.059419  0.711784  1.030253
22               paracentral_12R      HC -0.348940 -0.182466  0.012785
23               paracentral_12R     PSY -0.361884 -0.182466  0.012785
24                paracentral_2R      HC -0.262970  0.417041 -0.697123
25                paracentral_2R     PSY -0.200572  0.417041 -0.697123
26                paracentral_3R      HC -0.081008  0.524883  0.346867
27                paracentral_3R     PSY  0.040250  0.524883  0.346867
28                paracentral_4R      HC -0.339116  0.440245 -0.880085
29                paracentral_4R     PSY -0.168619  0.440245 -0.880085
30                paracentral_5R      HC -0.323080  0.410823 -0.797830
31                paracentral_5R     PSY -0.241307  0.410823 -0.797830
32         posteriorcingulate_2R      HC  0.498098  0.964522  2.018503
33         posteriorcingulate_2R     PSY  0.542523  0.964522  2.018503
34         posteriorcingulate_4R      HC  0.454029  1.301583  2.436121
35         posteriorcingulate_4R     PSY  0.509190  1.301583  2.436121
36         posteriorcingulate_7R      HC  0.407315  0.275994  1.535678
37         posteriorcingulate_7R     PSY  0.216732  0.275994  1.535678
38         posteriorcingulate_8R      HC -0.032001  0.245696  1.537081
39         posteriorcingulate_8R     PSY  0.027484  0.245696  1.537081
40                 precuneus_11R      HC  0.096367 -0.091640  0.698700
41                 precuneus_11R     PSY  0.025430 -0.091640  0.698700
42                 precuneus_12R      HC  0.723783  1.180773  1.875148
43                 precuneus_12R     PSY  0.702435  1.180773  1.875148
44                 precuneus_13R      HC -0.237122 -0.789179 -0.300498
45                 precuneus_13R     PSY -0.142104 -0.789179 -0.300498
46                 precuneus_14R      HC  0.104073  0.198723  0.613765
47                 precuneus_14R     PSY  0.122900  0.198723  0.613765
48                 precuneus_15R      HC  0.217831  0.180437  1.016334
49                 precuneus_15R     PSY  0.361763  0.180437  1.016334
50                 precuneus_18R      HC  0.069824  0.319077  0.838245
51                 precuneus_18R     PSY  0.013118  0.319077  0.838245
52                 precuneus_21R      HC  0.288248  1.309920  1.946343
53                 precuneus_21R     PSY  0.543967  1.309920  1.946343
54                 precuneus_22R      HC  0.540372  1.023328  1.390269
55                 precuneus_22R     PSY  0.679928  1.023328  1.390269
56                  precuneus_5R      HC  0.342587  1.117213  2.026524
57                  precuneus_5R     PSY  0.467174  1.117213  2.026524
58                  precuneus_7R      HC  0.427186 -0.309226  0.882409
59                  precuneus_7R     PSY  0.457342 -0.309226  0.882409
60                  precuneus_8R      HC  0.379717  0.818042  1.321591
61                  precuneus_8R     PSY  0.412000  0.818042  1.321591
62   rostralanteriorcingulate_3R      HC -0.210773  0.640998  2.365694
63   rostralanteriorcingulate_3R     PSY -0.207022  0.640998  2.365694
64           superiorfrontal_10R      HC -0.686587 -1.153023  0.210343
65           superiorfrontal_10R     PSY -0.511042 -1.153023  0.210343
66           superiorfrontal_12R      HC -0.479986  0.061648 -0.045458
67           superiorfrontal_12R     PSY -0.599090  0.061648 -0.045458
68           superiorfrontal_17R      HC -0.294645  0.427016  0.062218
69           superiorfrontal_17R     PSY -0.192140  0.427016  0.062218
70           superiorfrontal_18R      HC -0.367414  0.335339  0.842875
71           superiorfrontal_18R     PSY -0.430914  0.335339  0.842875
72            superiorfrontal_1R      HC -0.251715  0.986866  1.879627
73            superiorfrontal_1R     PSY -0.307890  0.986866  1.879627
74           superiorfrontal_20R      HC -0.710588 -0.566945 -0.444607
75           superiorfrontal_20R     PSY -0.833274 -0.566945 -0.444607
76           superiorfrontal_23R      HC -0.611159 -1.152823  0.333563
77           superiorfrontal_23R     PSY -0.574892 -1.152823  0.333563
78           superiorfrontal_24R      HC  0.102619  0.540498  1.204780
79           superiorfrontal_24R     PSY  0.013735  0.540498  1.204780
80           superiorfrontal_25R      HC  0.074453  0.700920  1.659291
81           superiorfrontal_25R     PSY -0.125483  0.700920  1.659291
82           superiorfrontal_29R      HC -0.659061 -0.244781  0.447170
83           superiorfrontal_29R     PSY -0.689234 -0.244781  0.447170
84           superiorfrontal_30R      HC -0.237565  0.900524  1.696054
85           superiorfrontal_30R     PSY -0.323895  0.900524  1.696054
86           superiorfrontal_31R      HC -0.015472  0.532322  0.770870
87           superiorfrontal_31R     PSY  0.102392  0.532322  0.770870
88           superiorfrontal_32R      HC -0.308634 -0.262348 -0.484805
89           superiorfrontal_32R     PSY -0.428491 -0.262348 -0.484805
90           superiorfrontal_36R      HC -0.930875 -0.392232 -0.032582
91           superiorfrontal_36R     PSY -0.833287 -0.392232 -0.032582
92           superiorfrontal_38R      HC -0.674849  0.765280  0.672350
93           superiorfrontal_38R     PSY -0.543777  0.765280  0.672350
94           superiorfrontal_39R      HC -0.700630 -0.539328  0.194108
95           superiorfrontal_39R     PSY -0.550927 -0.539328  0.194108
96           superiorfrontal_40R      HC -0.663181 -1.089619  0.456369
97           superiorfrontal_40R     PSY -0.543902 -1.089619  0.456369
98            superiorfrontal_7R      HC -0.223221  0.739121  1.834678
99            superiorfrontal_7R     PSY -0.455633  0.739121  1.834678
100           superiorfrontal_8R      HC -0.857712 -0.331275 -0.129873
101           superiorfrontal_8R     PSY -0.800876 -0.331275 -0.129873
102           superiorfrontal_9R      HC -0.154002 -0.293822 -0.660154
103           superiorfrontal_9R     PSY -0.372532 -0.293822 -0.660154

         GABA       Lobe
0   -0.473436    frontal
1   -0.473436    frontal
2    0.654213  occipital
3    0.654213  occipital
4    1.635019  occipital
5    1.635019  occipital
6   -1.099287    frontal
7   -1.099287    frontal
8    0.020157   parietal
9    0.020157   parietal
10   1.778774   parietal
11   1.778774   parietal
12  -0.337078   parietal
13  -0.337078   parietal
14  -0.362558   parietal
15  -0.362558   parietal
16   2.226812  occipital
17   2.226812  occipital
18   2.717434  occipital
19   2.717434  occipital
20   0.575877    frontal
21   0.575877    frontal
22  -0.030164    frontal
23  -0.030164    frontal
24  -0.772528    frontal
25  -0.772528    frontal
26  -0.037938    frontal
27  -0.037938    frontal
28  -0.991449    frontal
29  -0.991449    frontal
30  -1.259601    frontal
31  -1.259601    frontal
32   1.153688   parietal
33   1.153688   parietal
34   1.839936   parietal
35   1.839936   parietal
36   0.244912   parietal
37   0.244912   parietal
38   0.111029   parietal
39   0.111029   parietal
40   0.325132   parietal
41   0.325132   parietal
42   2.280131   parietal
43   2.280131   parietal
44  -0.584393   parietal
45  -0.584393   parietal
46   0.126787   parietal
47   0.126787   parietal
48   1.082489   parietal
49   1.082489   parietal
50   0.836535   parietal
51   0.836535   parietal
52   1.802124   parietal
53   1.802124   parietal
54   2.208944   parietal
55   2.208944   parietal
56   1.556831   parietal
57   1.556831   parietal
58   1.404110   parietal
59   1.404110   parietal
60   1.141556   parietal
61   1.141556   parietal
62   1.416093    frontal
63   1.416093    frontal
64  -0.108241    frontal
65  -0.108241    frontal
66   0.015555    frontal
67   0.015555    frontal
68  -0.333939    frontal
69  -0.333939    frontal
70   0.778091    frontal
71   0.778091    frontal
72   1.213349    frontal
73   1.213349    frontal
74  -0.603468    frontal
75  -0.603468    frontal
76  -0.651593    frontal
77  -0.651593    frontal
78   0.359173    frontal
79   0.359173    frontal
80   0.952445    frontal
81   0.952445    frontal
82   0.213661    frontal
83   0.213661    frontal
84   1.118223    frontal
85   1.118223    frontal
86   0.375537    frontal
87   0.375537    frontal
88  -0.469178    frontal
89  -0.469178    frontal
90   0.069995    frontal
91   0.069995    frontal
92   0.235748    frontal
93   0.235748    frontal
94  -0.184789    frontal
95  -0.184789    frontal
96  -0.236281    frontal
97  -0.236281    frontal
98   1.177836    frontal
99   1.177836    frontal
100 -0.108921    frontal
101 -0.108921    frontal
102 -0.651477    frontal
103 -0.651477    frontal

### Data Imputation

In [17]:
# Now, for the long_dfs, impute data based on average across participants for that parcel
# Subject-wise data
merged_df = pd.merge(long_df, grouped_subj[['Parcel', 'hstatus', 'CEST_avg', 'NMDA', 'GABA', 'mGluR5']], on=['Parcel', 'hstatus'], how='left')
#print(merged_df)
merged_df['GluCEST'] = merged_df['GluCEST'].fillna(merged_df['CEST_avg'])
merged_df['NMDA'] = merged_df['NMDA_x'].fillna(merged_df['NMDA_y'])
merged_df['GABA'] = merged_df['GABA_x'].fillna(merged_df['GABA_y'])
merged_df['mGluR5'] = merged_df['mGluR5_x'].fillna(merged_df['mGluR5_y'])
#print(merged_df)
imputed_df = merged_df.drop(columns=['CEST_avg', 'NMDA_x', 'NMDA_y', 'GABA_x', 'GABA_y','mGluR5_x', 'mGluR5_y'])

# Standard data
# First, rename parcels
long_df_std["Parcel"] = long_df_std["Parcel"].str.replace(' NZMean', '', regex=False)
grouped_subj_std = grouped_subj.copy()
grouped_subj_std["Parcel"] = grouped_subj_std["Parcel"].str.replace(' NZMean', '', regex=False)
#print(long_df_std)
merged_df_std = pd.merge(long_df_std, grouped_subj_std[['Parcel', 'hstatus', 'CEST_avg']], on=['Parcel', 'hstatus'], how='left')
merged_df_std['GluCEST'] = merged_df_std ['GluCEST'].fillna(merged_df_std ['CEST_avg'])
#print(merged_df_std)
imputed_df_std = merged_df_std.drop(columns=['CEST_avg'])

imputed_df.to_csv(outpath + '/imputed_long_df_' + dataset + '_' + atlas + '.csv', index=False)
imputed_df_std.to_csv(outpath + '/imputed_long_df_standardnmaps_' + dataset + '_' + atlas + '.csv', index=False)

### Normalize GluCEST values

In [38]:
# Make mean group dfs by diagnosis
# Standard nmap data
grouped_std = long_df_std.groupby(['Parcel', 'hstatus']).agg(
    CEST_avg=('GluCEST', 'mean'),
    NMDA_avg=('NMDA', 'mean'),
    mGluR5_avg=('mGluR5', 'mean'),
    GABA_avg=('GABA', 'mean')
).reset_index()
grouped_std = add_lobe(grouped_std)
print(grouped_std)
grouped_std.to_csv(outpath + '/means_std_normalized_cest_' + dataset + '_' + atlas + '.csv', index=False)

                          Parcel hstatus  CEST_avg  NMDA_avg  mGluR5_avg  \
0     caudalanteriorcingulate_5R      HC  0.140048 -0.026330    1.229935
1     caudalanteriorcingulate_5R     PSY -0.011085 -0.026330    1.229935
2                      cuneus_3R      HC  0.884299 -0.522157    0.053661
3                      cuneus_3R     PSY  0.305783 -0.522157    0.053661
4                      cuneus_5R      HC  1.411665  0.046650    0.220775
5                      cuneus_5R     PSY  0.963478  0.046650    0.220775
6                 frontalpole_1R      HC -0.475798 -2.137305   -0.306475
7                 frontalpole_1R     PSY  0.129303 -2.137305   -0.306475
8            isthmuscingulate_1R      HC  0.265007  0.862035    0.410423
9            isthmuscingulate_1R     PSY  0.302260  0.862035    0.410423
10           isthmuscingulate_2R      HC  0.592127  1.319292    1.994640
11           isthmuscingulate_2R     PSY  0.723430  1.319292    1.994640
12           isthmuscingulate_3R      HC  0.098472  0.358761   -0.140923
13           isthmuscingulate_3R     PSY  0.257665  0.358761   -0.140923
14           isthmuscingulate_4R      HC  0.246605  0.665040   -0.384585
15           isthmuscingulate_4R     PSY  0.520684  0.665040   -0.384585
16                   lingual_11R      HC  1.179280  0.894964   -0.389795
17                   lingual_11R     PSY  0.804932  0.894964   -0.389795
18                   lingual_13R      HC  1.987714  0.758787   -0.223504
19                   lingual_13R     PSY  1.432024  0.758787   -0.223504
20               paracentral_11R      HC -0.106498  0.711784    1.030253
21               paracentral_11R     PSY -0.059419  0.711784    1.030253
22               paracentral_12R      HC -0.348940 -0.182466    0.012785
23               paracentral_12R     PSY -0.361884 -0.182466    0.012785
24                paracentral_2R      HC -0.262970  0.417041   -0.697123
25                paracentral_2R     PSY -0.200572  0.417041   -0.697123
26                paracentral_3R      HC -0.081008  0.524883    0.346867
27                paracentral_3R     PSY  0.040250  0.524883    0.346867
28                paracentral_4R      HC -0.339116  0.440245   -0.880085
29                paracentral_4R     PSY -0.168619  0.440245   -0.880085
30                paracentral_5R      HC -0.323080  0.410823   -0.797830
31                paracentral_5R     PSY -0.241307  0.410823   -0.797830
32         posteriorcingulate_2R      HC  0.498098  0.964522    2.018503
33         posteriorcingulate_2R     PSY  0.542523  0.964522    2.018503
34         posteriorcingulate_4R      HC  0.454029  1.301583    2.436121
35         posteriorcingulate_4R     PSY  0.509190  1.301583    2.436121
36         posteriorcingulate_7R      HC  0.407315  0.275994    1.535678
37         posteriorcingulate_7R     PSY  0.216732  0.275994    1.535678
38         posteriorcingulate_8R      HC -0.032001  0.245696    1.537081
39         posteriorcingulate_8R     PSY  0.027484  0.245696    1.537081
40                 precuneus_11R      HC  0.096367 -0.091640    0.698700
41                 precuneus_11R     PSY  0.025430 -0.091640    0.698700
42                 precuneus_12R      HC  0.723783  1.180773    1.875148
43                 precuneus_12R     PSY  0.702435  1.180773    1.875148
44                 precuneus_13R      HC -0.237122 -0.789179   -0.300498
45                 precuneus_13R     PSY -0.142104 -0.789179   -0.300498
46                 precuneus_14R      HC  0.104073  0.198723    0.613765
47                 precuneus_14R     PSY  0.122900  0.198723    0.613765
48                 precuneus_15R      HC  0.217831  0.180437    1.016334
49                 precuneus_15R     PSY  0.361763  0.180437    1.016334
50                 precuneus_18R      HC  0.069824  0.319077    0.838245
51                 precuneus_18R     PSY  0.013118  0.319077    0.838245
52                 precuneus_21R      HC  0.288248  1.309920    1.946343
53                 precuneus_21R     PSY  0.543967  1.309920    1.946343
54                 precuneus_22R      HC  0.540372  1.023328    1.390269
55                 precuneus_22R     PSY  0.679928  1.023328    1.390269
56                  precuneus_5R      HC  0.342587  1.117213    2.026524
57                  precuneus_5R     PSY  0.467174  1.117213    2.026524
58                  precuneus_7R      HC  0.427186 -0.309226    0.882409
59                  precuneus_7R     PSY  0.457342 -0.309226    0.882409
60                  precuneus_8R      HC  0.379717  0.818042    1.321591
61                  precuneus_8R     PSY  0.412000  0.818042    1.321591
62   rostralanteriorcingulate_3R      HC -0.210773  0.640998    2.365694
63   rostralanteriorcingulate_3R     PSY -0.207022  0.640998    2.365694
64           superiorfrontal_10R      HC -0.686587 -1.153023    0.210343
65           superiorfrontal_10R     PSY -0.511042 -1.153023    0.210343
66           superiorfrontal_12R      HC -0.479986  0.061648   -0.045458
67           superiorfrontal_12R     PSY -0.599090  0.061648   -0.045458
68           superiorfrontal_17R      HC -0.294645  0.427016    0.062218
69           superiorfrontal_17R     PSY -0.192140  0.427016    0.062218
70           superiorfrontal_18R      HC -0.367414  0.335339    0.842875
71           superiorfrontal_18R     PSY -0.430914  0.335339    0.842875
72            superiorfrontal_1R      HC -0.251715  0.986866    1.879627
73            superiorfrontal_1R     PSY -0.307890  0.986866    1.879627
74           superiorfrontal_20R      HC -0.710588 -0.566945   -0.444607
75           superiorfrontal_20R     PSY -0.833274 -0.566945   -0.444607
76           superiorfrontal_23R      HC -0.611159 -1.152823    0.333563
77           superiorfrontal_23R     PSY -0.574892 -1.152823    0.333563
78           superiorfrontal_24R      HC  0.102619  0.540498    1.204780
79           superiorfrontal_24R     PSY  0.013735  0.540498    1.204780
80           superiorfrontal_25R      HC  0.074453  0.700920    1.659291
81           superiorfrontal_25R     PSY -0.125483  0.700920    1.659291
82           superiorfrontal_29R      HC -0.659061 -0.244781    0.447170
83           superiorfrontal_29R     PSY -0.689234 -0.244781    0.447170
84           superiorfrontal_30R      HC -0.237565  0.900524    1.696054
85           superiorfrontal_30R     PSY -0.323895  0.900524    1.696054
86           superiorfrontal_31R      HC -0.015472  0.532322    0.770870
87           superiorfrontal_31R     PSY  0.102392  0.532322    0.770870
88           superiorfrontal_32R      HC -0.308634 -0.262348   -0.484805
89           superiorfrontal_32R     PSY -0.428491 -0.262348   -0.484805
90           superiorfrontal_36R      HC -0.930875 -0.392232   -0.032582
91           superiorfrontal_36R     PSY -0.833287 -0.392232   -0.032582
92           superiorfrontal_38R      HC -0.674849  0.765280    0.672350
93           superiorfrontal_38R     PSY -0.543777  0.765280    0.672350
94           superiorfrontal_39R      HC -0.700630 -0.539328    0.194108
95           superiorfrontal_39R     PSY -0.550927 -0.539328    0.194108
96           superiorfrontal_40R      HC -0.663181 -1.089619    0.456369
97           superiorfrontal_40R     PSY -0.543902 -1.089619    0.456369
98            superiorfrontal_7R      HC -0.223221  0.739121    1.834678
99            superiorfrontal_7R     PSY -0.455633  0.739121    1.834678
100           superiorfrontal_8R      HC -0.857712 -0.331275   -0.129873
101           superiorfrontal_8R     PSY -0.800876 -0.331275   -0.129873
102           superiorfrontal_9R      HC -0.154002 -0.293822   -0.660154
103           superiorfrontal_9R     PSY -0.372532 -0.293822   -0.660154

     GABA_avg       Lobe
0   -0.473436    frontal
1   -0.473436    frontal
2    0.654213  occipital
3    0.654213  occipital
4    1.635019  occipital
5    1.635019  occipital
6   -1.099287    frontal
7   -1.099287    frontal
8    0.020157   parietal
9    0.020157   parietal
10   1.778774   parietal
11   1.778774   parietal
12  -0.337078   parietal
13  -0.337078   parietal
14  -0.362558   parietal
15  -0.362558   parietal
16   2.226812  occipital
17   2.226812  occipital
18   2.717434  occipital
19   2.717434  occipital
20   0.575877    frontal
21   0.575877    frontal
22  -0.030164    frontal
23  -0.030164    frontal
24  -0.772528    frontal
25  -0.772528    frontal
26  -0.037938    frontal
27  -0.037938    frontal
28  -0.991449    frontal
29  -0.991449    frontal
30  -1.259601    frontal
31  -1.259601    frontal
32   1.153688   parietal
33   1.153688   parietal
34   1.839936   parietal
35   1.839936   parietal
36   0.244912   parietal
37   0.244912   parietal
38   0.111029   parietal
39   0.111029   parietal
40   0.325132   parietal
41   0.325132   parietal
42   2.280131   parietal
43   2.280131   parietal
44  -0.584393   parietal
45  -0.584393   parietal
46   0.126787   parietal
47   0.126787   parietal
48   1.082489   parietal
49   1.082489   parietal
50   0.836535   parietal
51   0.836535   parietal
52   1.802124   parietal
53   1.802124   parietal
54   2.208944   parietal
55   2.208944   parietal
56   1.556831   parietal
57   1.556831   parietal
58   1.404110   parietal
59   1.404110   parietal
60   1.141556   parietal
61   1.141556   parietal
62   1.416093    frontal
63   1.416093    frontal
64  -0.108241    frontal
65  -0.108241    frontal
66   0.015555    frontal
67   0.015555    frontal
68  -0.333939    frontal
69  -0.333939    frontal
70   0.778091    frontal
71   0.778091    frontal
72   1.213349    frontal
73   1.213349    frontal
74  -0.603468    frontal
75  -0.603468    frontal
76  -0.651593    frontal
77  -0.651593    frontal
78   0.359173    frontal
79   0.359173    frontal
80   0.952445    frontal
81   0.952445    frontal
82   0.213661    frontal
83   0.213661    frontal
84   1.118223    frontal
85   1.118223    frontal
86   0.375537    frontal
87   0.375537    frontal
88  -0.469178    frontal
89  -0.469178    frontal
90   0.069995    frontal
91   0.069995    frontal
92   0.235748    frontal
93   0.235748    frontal
94  -0.184789    frontal
95  -0.184789    frontal
96  -0.236281    frontal
97  -0.236281    frontal
98   1.177836    frontal
99   1.177836    frontal
100 -0.108921    frontal
101 -0.108921    frontal
102 -0.651477    frontal
103 -0.651477    frontal

In [19]:
# Step 1: Select columns that contain 'NZMean'
nzmean_columns = [col for col in cestmat.columns if 'NZMean' in col]

# Step 2: Calculate mean and std deviation for each subject (row-wise) across selected columns
cestmat['Subject_Avg_NZMean'] = cestmat[nzmean_columns].mean(axis=1)
cestmat['Subject_Std_NZMean'] = cestmat[nzmean_columns].std(axis=1)

# Step 3: Calculate z-scores for all selected columns at once and store them in a new dataframe
zscore_df = (cestmat[nzmean_columns].sub(cestmat['Subject_Avg_NZMean'], axis=0)
             .div(cestmat['Subject_Std_NZMean'], axis=0))

# Rename z-score columns
zscore_df.columns = [col + '_Zscore' for col in zscore_df.columns]
#print(zscore_df.size)
#print(zscore_df)
# Step 4: Concatenate the z-scores dataframe to the original cestmat dataframe
zcestmat = pd.concat([cestmat['group'], zscore_df], axis=1)

zcestmat.to_csv(outpath + '/grp_df_means_std_normalized_' + dataset + '_' + atlas + '.csv', index=False)
#print(zcestmat)

In [40]:
cestmat2=cestmat.copy()
NMDAmat2=NMDAmat.copy()
GABAmat2=GABAmat.copy()
mGluR5mat2=mGluR5mat.copy()
cestmat2.columns = [f"GluCEST_{col}" if "NZ" in col else col for col in cestmat2.columns]
NMDAmat2.columns = [f"NMDA_{col}" if "NZ" in col else col for col in NMDAmat2.columns]
GABAmat2.columns = [f"GABA_{col}" if "NZ" in col else col for col in GABAmat2.columns]
mGluR5mat2.columns = [f"mGluR5_{col}" if "NZ" in col else col for col in mGluR5mat2.columns]

# Align dataframes by "Subject" index and concatenate along columns
grp_df = cestmat2.join(NMDAmat2.filter(like='NZ'), how='left')
grp_df = grp_df.join(GABAmat2.filter(like='NZ'), how='left')
grp_df = grp_df.join(mGluR5mat2.filter(like='NZ'), how='left')

#grp_df = add_lobe(grp_df)

# Save grp_df
grp_df.to_csv(outpath + '/grp_df_' + dataset + atlas + '.csv', index=True)